var searchTerm;
var id;

//function called if button is clicked
function searched(){
  document.getElementById("query-1").innerHTML = "";
  //points a reference to the element in the search
  var searchedWord = document.getElementById("searchTerm").value;
  searchTerm = searchedWord;
    document.getElementById("searchTerm").value ="";
    newElement("p", "You searched for '" + searchedWord +"'", 'result', 'query-1');

  //uses a function to receive search data from 2 different sources in API
  getResults("Fast+Foods", searchedWord, 0);
  getResults("Restaurant+Foods", searchedWord, 1000);
  }

//creates an element
//parameter: element - type of element
//elText - value of element/ thisname - name of element/ parentElement - parent reference
newElement = function(element, elText,thisname, parentElement){
  //points to new node
  var newEl = document.createElement(element);
  //creates a value
  var newContent = document.createTextNode(elText);
  //sets node's value to newContent
  newEl.appendChild(newContent);
  var parent = document.getElementById(parentElement);
  //sets a reference from the parent element to the new element(so it become a part of webpage)
  parent.appendChild(newEl);
  //sets the names
  newEl.id = thisname;
}

//gathers the data from the api and adds it to the page
getResults = function(foodType, searchedFood, queryStart){
    let j = queryStart;
    let request = new XMLHttpRequest();
      let url = "https://api.nal.usda.gov/ndb/search/?format=json";
      url+=("&q="+searchedFood);
      url+=("&sort=n&fg="+ foodType + "&api_key=FWaQH04Azwkd2GABmQTRrox5VMNSkhJrHfYpgxMG");
      //event listener
      request.onreadystatechange = function() {
        //when the API server is ready, receive and add the elements to the page
        if (this.readyState === 4 && this.status === 200) {
          let response = JSON.parse(this.responseText);
          for(var i = 0; i < JSON.stringify(response.list.item.length); i++){
            //alert(JSON.stringify(response.list.item[i].name));
            newElement("p", JSON.stringify(response.list.item[i].name),'query'+j, 'query-1');
            var currElement = document.getElementById('query'+j);
            j++;
            //styling the page through javascript
            currElement.style.height = "175px";
            currElement.style.paddingTop = "12px";
            currElement.style.backgroundColor = "rgb(212,18,116)";
            currElement.style.float = "left";
            currElement.style.width = "49%";
            currElement.style.color = "white";
            //add a button to the search query that can be clicked and create a popup
            currElement.innerHTML+="<br>";
            currElement.innerHTML+='<button type="submit" onclick = "dialog('+(j-1)+'); return false;" class = "magentabtn"><i class="fa fa-plus-square-o"></i></button>';
            //spacing between the elements
            if((i%2)===1){
              currElement.style.marginLeft = "10px";
            }
          }
        }
      }
      //sends and creates the request
      request.open("GET", url, true);
      request.send();
  }

//opens the popup page if button is clicked
//parameter x - integer number identifier to find specific element
dialog = function(x){
  var searchKey = document.getElementById('query' + x + '');
  var term = searchKey.innerText;
  var modal = document.getElementById('popUp');
  modal.style.display = "block";
  var fixed = isolateName(term);
  document.getElementById("innerText").innerText = term.substring(1, term.length - 2);
  postToPopUp(fixed);
} 

//closes the popup page if 'x' is click
function exit(){
  var modal = document.getElementById('popUp');
  modal.style.display = "none";
}

//takes data from the API and adds it to the popup page
//parameter keyword  - name of the fast food branch
function postToPopUp(keyWord){
  let bodyText = document.getElementById("innerText");
  let headBanner = document.getElementById('banner');
  
  if(keyWord.search("School Lunch") !== -1){
    //adds default image and text for generic school lunch query
    bodyText.innerHTML+= '<img src = "schoolLunch.png" alt = "school Lunch" style = "width : 50%; height : 50%;">';
    bodyText.innerHTML+="<br>";
    bodyText.innerText+= 'This is an autogenerated generic food item typically available at school facilities.'
    bodyText.innerHTML+="<br>";
    bodyText.innerText+= 'We cannot guarantee its availability and prices will vary';
    bodyText.innerHTML+="<br>";
    bodyText.innerText+= 'For more information, contact your school facilities';
    bodyText.innerHTML+="<br>";
    headBanner.innerText = keyWord;
    
  }else if((keyWord.search("Fast foods")!== -1) || (keyWord.search("Fast Food") !== -1)){
    //adds default image and text for generic fast food quesy
    bodyText.innerHTML+= '<img src = "fastfood.png" alt = "fast food" style = "width : 30%; height : 30%;">';
    headBanner.innerText = keyWord;
  }else if((keyWord.search("Restaurant")!== -1))  {
    //adds default image and text for generic restaurant query
    headBanner.innerText = keyWord;
    bodyText.innerHTML+= '<img src = "restaurant_food.png" alt = "restaurant food" style = "width : 30%; height : 30%;">';
  }else {
    //custom search and result
  addImage(keyWord);
    getDetails(keyWord);

 

}
}

//uses the foursquare api to generate general venue details
//calls the method getInfo using the parameter place ID to provide specific detail
function getDetails(keyTerm){
  var placeId = "";
  let request = new XMLHttpRequest();
  let url = "https://api.foursquare.com/v2/venues/search/?near=San+Francisco&query=";
  url+=keyTerm;
  url+="&limit=1&client_id=NBVZZZSD5QBEA2SWONO22JHPQ3YUDJAHT3N4U4JYUSDSP0D3&client_secret=KP5HBRJX2Z3R3FJFJSMFT0SEGBN4TFRCZETYLKANOL5UMLCF&v=20180522";
  request.onreadystatechange = function() {
    //when the API server is ready, receive and add the elements to the page
    if (request.readyState === 4 && request.status === 200) {
      let response = JSON.parse(request.responseText);
      placeId = response.response.venues[0].id;
      getInfo(placeId);
      
    }
  }
  request.open("GET", url, true);
  request.send();
  
}

//returns data on a specific store(currently test case - near San Francisco)
//parameter id - specific store id created by foursquare
function getInfo(id){
  alert(id); 
  let req = new XMLHttpRequest();
  let popUpText= document.getElementById('innerText');
  let link = "https://api.foursquare.com/v2/venues/" + id;
  link+="?client_id=NBVZZZSD5QBEA2SWONO22JHPQ3YUDJAHT3N4U4JYUSDSP0D3&client_secret=KP5HBRJX2Z3R3FJFJSMFT0SEGBN4TFRCZETYLKANOL5UMLCF&v=20180522";
  req.onreadystatechange = function(){
    //when the API server is ready, receive and add the elements to the page
    if(req.readyState === 4 && req.status === 200){
      let resp = JSON.parse(req.response);
      popUpText.innerText+= JSON.stringify(resp);
      alert("success");
    }
  }
  req.open("GET", link, true);
  req.send();
}


//isolates only the store brand name, not the food and the place - removes the " " and ,
function isolateName(keyWord){
let comma = keyWord.indexOf(",");
let newWord = keyWord.substring(1, comma);
return newWord;
}


//adds images using the flickr API
function addImage(location){

var request = new XMLHttpRequest();
//url link
var url = "https://api.flickr.com/services/rest/?method=flickr.photos.search&text=";
url+= location + "+" + searchTerm;
url+= "&per_page=1&sort=relevance&api_key=e1146b5612636a385b211ecc4891014f&format=json&nojsoncallback=1";
request.onreadystatechange = function() {
  //when the API server is ready, receive and add the elements to the page
  if (request.readyState === 4 && request.status === 200) {
    let response = JSON.parse(request.responseText);
    if(response.photos.photo[0]!==(null)){
      //opening the text
    let dataSet = response.photos.photo[0];
    //generating the custom url for the picture
    let imageSrc = "https://farm" + dataSet.farm + ".staticflickr.com/" + dataSet.server;
    imageSrc+= "/" + dataSet.id + "_" + dataSet.secret + "_n.jpg";
    //appending the image to the popup
    let thumbNail = document.getElementById("innerText");
    thumbNail.innerHTML+='<br><img src ="' + imageSrc + '" alt = "foodPic">';
    }
}
}
request.open("GET", url, true);
request.send();
}